# Generated by Django 5.2.4 on 2025-08-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="center",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.IntegerField(max_length=6)),
                ("short_name", models.CharField(max_length=3)),
                ("name", models.CharField(max_length=50)),
                ("phone", models.IntegerField(max_length=11)),
                ("village", models.CharField(max_length=20)),
            ],
        ),
    ]
