# Generated by Django 5.2.4 on 2025-08-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField(max_length=3)),
                ("number_prefix", models.IntegerField(max_length=3)),
                ("first_name", models.CharField(max_length=10)),
                ("last_name", models.CharField(max_length=10)),
                ("gender", models.BooleanField()),
                ("dob", models.DateTimeField()),
                ("mobile", models.IntegerField()),
            ],
        ),
    ]
