# Generated by Django 5.2.4 on 2025-08-05 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0002_customer"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField()),
                (
                    "type",
                    models.CharField(
                        choices=[("c", "Cow"), ("b", "buffalo")], max_length=1
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[("M", "Morning"), ("E", "Evening")], max_length=1
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=3)),
                ("snf", models.DecimalField(decimal_places=1, max_digits=1)),
                ("fat", models.DecimalField(decimal_places=1, max_digits=1)),
                ("rate", models.DecimalField(decimal_places=2, max_digits=2)),
            ],
        ),
    ]
