# Generated by Django 5.2.4 on 2025-08-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0003_collection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collection",
            name="fat",
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
        migrations.AlterField(
            model_name="collection",
            name="snf",
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
