# Generated by Django 5.2.4 on 2025-08-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0005_alter_collection_fat_alter_collection_rate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="center",
            name="code",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="center",
            name="phone",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="number_prefix",
            field=models.IntegerField(),
        ),
    ]
