# Generated by Django 5.2.4 on 2025-08-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0006_alter_center_code_alter_center_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="center",
            name="code",
            field=models.IntegerField(null=True),
        ),
    ]
