# Generated by Django 5.2.4 on 2025-08-07 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0007_alter_center_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="center",
            name="code",
            field=models.IntegerField(default=25),
            preserve_default=False,
        ),
    ]
