# Generated by Django 5.2.4 on 2025-08-08 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0008_alter_center_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="status",
            field=models.IntegerField(
                choices=[("1", "Active"), ("2", "Inactive"), ("3", "deleted")],
                default=2,
                max_length=1,
            ),
        ),
    ]
