# Generated by Django 5.2.4 on 2025-08-08 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0009_center_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="center",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Active"), (2, "Inactive"), (3, "Deleted")],
                default=2,
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.IntegerField(choices=[(1, "Male"), (2, "Female")]),
        ),
    ]
