# Generated by Django 5.2.4 on 2025-08-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0010_alter_center_status_alter_customer_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="gender",
            field=models.IntegerField(choices=[(1, "Male"), (2, "Female")], default=1),
        ),
    ]
