# Generated by Django 5.2.4 on 2025-08-08 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0011_alter_customer_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Active"), (2, "Non Active"), (3, "deleted")], default=1
            ),
        ),
    ]
