# Generated by Django 5.2.4 on 2025-08-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0012_customer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Active"), (2, "Non Active"), (3, "deleted")], default=1
            ),
        ),
    ]
