# Generated by Django 5.2.4 on 2025-08-11 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0013_collection_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="centers",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                to="firstapp.center",
            ),
        ),
    ]
