# Generated by Django 5.2.4 on 2025-08-11 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0014_collection_centers"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="centers",
        ),
        migrations.AddField(
            model_name="collection",
            name="center",
            field=models.ForeignKey(
                default=5,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="centers",
                to="firstapp.center",
            ),
        ),
    ]
