# Generated by Django 5.2.4 on 2025-08-14 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("firstapp", "0015_remove_collection_centers_collection_center"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="customer",
            field=models.ForeignKey(
                default=10,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="customer",
                to="firstapp.customer",
            ),
        ),
    ]
